import { sharedTheme } from "@/styles/sharedTheme";

const modernTheme = {
  templateName: "modern",
  ...sharedTheme,
  colors: {
    background: "#ffffff",
    backgroundSecondary: "#f7f9fc",
    backgroundAlt: "#f0f2f5",
    sectionBackground: "#f7f9fc",
    inputBackground: "#ffffff",
    text: "#1f1f1f",
    textAlt: "#2e2e2e",
    textSecondary: "#6b7280",
    textPrimary: "#111827",
    primary: "#6366f1",
    primaryLight: "#eef2ff",
    primaryHover: "#4f46e5",
    primaryDark: "#4338ca",
    accent: "#3b82f6",
    secondary: "#64748b",
    border: "#d1d5db",
    cardBackground: "#ffffff",
    buttonBackground: "#6366f1",
    buttonText: "#ffffff",
    link: "#3b82f6",
    linkHover: "#1d4ed8",
    hoverBackground: "#f1f5f9",
    whiteColor: "#ffffff",
    darkColor: "#000000",
    success: "#22c55e",
    warning: "#facc15",
    danger: "#ef4444",
    info: "#0ea5e9",
    muted: "#9ca3af",
    disabled: "#e5e7eb",
  },
  buttons: {
    primary: {
      background: "#6366f1",
      backgroundHover: "#4f46e5",
      text: "#ffffff",
      textHover: "#ffffff",
    },
    secondary: {
      background: "#e5e7eb",
      backgroundHover: "#d1d5db",
      text: "#374151",
      textHover: "#1f2937",
    },
    danger: {
      background: "#ef4444",
      backgroundHover: "#dc2626",
      text: "#ffffff",
      textHover: "#ffffff",
    },
  },
  inputs: {
    background: "#ffffff",
    border: "#d1d5db",
    text: "#111827",
    placeholder: "#9ca3af",
  },
  cards: {
    background: "#ffffff",
    hoverBackground: "#f9fafb",
  },
};

export default modernTheme;
